---
title: "Statistical anaysis for: Latent and incubation periods of cowpea aphid-borne mosaic virus in passionflower and efficacy of roguing of infected plants as an alternative for disease management in the field"
author: "Spadotti et al., 2019"
output:
  html_document:
    theme: readable
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
options(width = 90)
library(tidyverse)
# modeling packages 
library(car)
library(epiDisplay)
library(sjPlot)
library(gmodels)
```

## Latent period

```{r}
load(here::here("data/lat_dat.RData"))

da <- dat %>% 
  group_by(iso, exp, days) %>%
  summarise(total= n(),
            infected = sum(positives)) %>% 
  ungroup

dat %>% 
  ggplot(aes(days, positives, col = iso)) +
  geom_point() +
  geom_smooth(method = "glm", se = F, fullrange=TRUE,
              method.args = list(family = "binomial"))+
# stat_summary(aes(y = infected/total, col=iso), 
#              fun.y=mean, geom="line") + 

  ggtitle("Latent period")
```

```{r latent_tiff, eval=FALSE}
source(here::here('0-themes.R'))

latent <- da %>% 
   mutate(iso= fct_recode(iso,
                          `CABMV-BA` = "BA", 
                          `CABMV-RJ` = "RJ",
                          `CABMV-SP` = "SP")) %>% 
  ggplot(aes(x = days, y = infected/total, col=iso, shape=iso))+
  geom_smooth(method = "glm", se = F, fullrange=FALSE, size=0.8,
              method.args = list(family = "binomial"))+
  geom_jitter(position=position_dodge(width=0.1),
              size = 1, colour="black", alpha=0.5)+
  theme_juan(8.8, "top")+
  scale_y_continuous(breaks=seq(0,1,.5))+
  scale_color_manual(values= c("black", "grey70", "grey90"))+
                     # labels = c("Bahia", "Rio do Janeiro", "São Paulo"))+ 
  labs(x="", 
       y="Proportion of plants that acted\nas source of CABMV inoculum\n", 
       col = "", 
       shape = "")+
  theme(legend.key.width=unit(1.2,"cm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0))# aspect.ratio = 1
latent
# ggsave(scale=2, units="mm", dpi=300, file = "./plots/latent.tiff", w=80, h=50)#
```

- SP como localidade de referencia

```{r}
dat %>% 
  mutate(iso = fct_relevel(iso, "SP", "BA","RJ")) %>%
  # filter(iso!="RJ") %>% 
  glm(positives ~ days*iso + exp,
      # weights=total, 
      family="binomial",
      data=.) -> mod 

summary(mod)
car::Anova(mod)
logistic.display(mod, decimal = 2, simplified=TRUE) #exp(coef(sp_2016))

cm <- rbind(
  'SP vs BA' = c(0, 0, 1, 0, 0, 1, 0),
  'SP vs RJ' = c(0, 0, 0, 1, 0, 0, 1),
  'BA vs RJ' = c(0, 0, 1,-1, 0, 1,-1)
  )
estimable(mod, cm)
plot_model(mod, type = "pred", terms = c("days", "iso"))

predict.glm(mod, data.frame(iso=c("SP", "BA", "RJ"), days=6, exp = 1.5), 
            type="response", se.fit=TRUE)

MASS::dose.p(mod,p=.5)

```

- BA como localidade de referencia

```{r}
dat %>% 
  glm(positives ~ days*iso,
      # weights=total, 
      family="binomial",
      data=.) -> mod1 

summary(mod1)
car::Anova(mod1)
logistic.display(mod1, decimal = 2, simplified=TRUE) #exp(coef(sp_2016))

# cm <- rbind(
#   'SP vs BA' = c(0, 0, 1, 0, 1, 0),
#   'SP vs RJ' = c(0, 0, 0, 1, 0, 1),
#   'BA vs RJ' = c(0, 0, 1, -1, 1, -1) 
#   )
# estimable(mod, cm)
# plot_model(mod, type = "pred", terms = c("days", "iso"))
```

## Incubation period

```{r}
load(here::here("data/incub_dat.RData"))
library(survival)
library(survminer)
```

```{r}
fit <- survfit(Surv(days,infected)~iso, data = incub)
# summary(fit)
print(fit)

summary(coxph(Surv(days,infected)~iso, data = incub))
surv_diff <- survdiff(Surv(days,infected)~iso, data = incub)
surv_diff
```

```{r}
ggsurvplot(fit, 
           surv.median.line="hv", 
           fun = 'event', 
           pval = F,  
           
           font.y = 8, font.tickslab = 8, fontsize=3, 
           
           legend.labs = c("CABMV-BA", "CABMV-RJ", "CABMV-SP"), 
           title="", 
           legend.title="Isolates",
           palette = c("black", "grey70", "grey90"), 
           
           xlab="Days after inoculation",
           break.y.by=0.5, 
           ylab="Cumulative proportion of symptomatic plants ",
           ggtheme = theme_bw(base_size=7))
```

```{r surv plot paper, eval = FALSE}
ggsurv <- ggsurvplot(fit, 
           surv.median.line="hv", 
           fun = 'event', 
           pval = F,  
           font.y = 9, font.tickslab = 8, fontsize=3, 
           legend = "none", 
           # title="", 
           # legend.title=NULL,
           palette = c("black", "grey70", "grey90"), 
           xlab="",
           break.y.by=0.5, 
           ylab="Cumulative proportion of symptomatic plants\n",
           ggtheme = theme_juan(9, "none"))

ggsurv$plot <- ggsurv$plot+ 
  annotate("text", x=25, y=.2,
           label = "Chisq = 1.6 \n P = 0.4", size = 2)+
  annotate("text", x=10, y=c(0.5,0.45), hjust = 0, 
           label = c("CABMV-BA & CABMV-SP: 7 days","CABMV-RJ: 8 days"), size=2)

aa <- ggpubr::ggarrange(latent, ggsurv$plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")

library(cowplot)

ggdraw(aa) + 
  draw_label("A", x=0.125, y=0.87, size=10, fontface="bold") + 
  draw_label("B", x=0.6, y=0.87, size=10, fontface="bold")+
  draw_label("Days after inoculation", x=0.53, y=0.03, size=10)

ggsave(last_plot(), file = "plots/latent_incub.tiff", w=160, h=80, units="mm", dpi=300, scale=1)
```

## Efficacy of rouguing 

```{r}
load(here::here("data/roug_dat.RData"))
load(here::here("roug_models.Rdata"))
```

```{r }
dat %>% 
  ggplot(aes(x = days, y = inf_plants/n_plants, col=type))+
  geom_point()+  
  geom_smooth(method = "glm", se = F, fullrange=FALSE, size=0.6,
              method.args = list(family = "binomial"))+
  scale_y_continuous(breaks=seq(0,1,.2), labels = function(x) paste0(x*100))+
  labs(x="Days after inoculation", y ="Infected plants (%)", 
       linetype = "Treatment", shape = "Treatment")+
  facet_wrap(~location:year)
```

```{r eval=FALSE}
p <- dat %>% 
  mutate(group=factor(paste0(location,"\n",year),
                      levels= c("SP\n2013","SP\n2016",
                                "BA\n2013","BA\n2014","BA\n2016")))%>% 
  ggplot(aes(x = days, y = inf_plants/n_plants, shape=type))+
  geom_smooth(method = "glm", se = F, fullrange=FALSE, size=0.8,
              method.args = list(family = "binomial"), 
              aes(col = type))+
  geom_point(aes(shape=type), size=2)+  
  scale_color_manual(values= c("grey10", "grey50", "grey80"))+
                     # labels = c("Bahia", "Rio do Janeiro", "São Paulo"))+ 
  # scale_linetype_manual(values=c("solid", "dotted", "dashed"))+ 
  scale_shape_manual(values=c(15, 16, 17))+
  theme_juan(12, "bottom")+
  scale_y_continuous(breaks=seq(0,1,.2), labels = function(x) paste0(x*100))+
  # scale_x_continuous(breaks=c(0,100, 200,300)) + 
  xlim(0,300)+
  labs(x="Days after transplant", y ="% of CABMV infected plants", 
       col = "Treatment", shape = "Treatment")+
  # annotate("text", 
  #           label = LETTERS[1:6] 
  #          # size=5, 
  #          # colour="black", fontface="bold", 
  #          # x=1, y=1, 
  #          # hjust="inward", vjust="inward"
           # )+
  facet_wrap(~group, ncol=2)+
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        legend.key.width=unit(0.75,"cm"),
        aspect.ratio = 1, legend.position= "none")#c(.8,.15)
library(egg)
tag_facet(p, 
          x = -Inf, y = Inf, 
          vjust = 2,
          open = "", close = "",
          tag_pool = LETTERS)

ggsave(scale=1, units="mm", dpi=200, file = "./plots/roug2.tiff", 
       w=160, h=200)#
```

### SP

* 2013 

```{r}
# library(DHARMa)
# simulation_sp_2013 <- simulateResiduals(fittedModel = sp_2013)
# plot(simulation_sp_2013)
modEvA::Dsquared(sp_2013)
Anova(sp_2013)
summary(sp_2013)
# plot_model(sp_2013, type = "pred", terms = c("days", "type"))
logistic.display(sp_2013, decimal = 2, simplified=TRUE)
cm1 <- rbind('Check vs Arbor'  = c(0, 0, 1, 1))
estimable(sp_2013, cm1)

```

* 2016 

```{r}
modEvA::Dsquared(sp_2016)
Anova(sp_2016)
summary(sp_2016)
logistic.display(sp_2016, decimal = 2, simplified=TRUE) #exp(coef(sp_2016))

cm2 <- rbind(
  'Check vs Arbor'   = c(0, 0, 1, 0, 1, 0),
  'Check vs Trellis' = c(0, 0, 0, 1, 0, 1), 
  'Arbor vs Trellis' = c(0, 0, 1, -1, 1, -1))
estimable(sp_2016, cm2)
```

### BA

* 2013 

```{r}
modEvA::Dsquared(ba_2013)
Anova(ba_2013)
summary(ba_2013)
# plot_model(ba_2013, type = "pred", terms = c("days", "type"))
logistic.display(ba_2013, decimal = 2, simplified=TRUE)
cm3 <- rbind('Check vs Arbor'  = c(0, 0, 1, 1))
estimable(ba_2013, cm3)
```

* 2014

```{r}
modEvA::Dsquared(ba_2014)
Anova(ba_2014)
summary(ba_2014)
cm4 <- rbind(
  'Check vs Arbor'  = c(0, 1, 0, 1))
estimable(ba_2014, cm4)
# plot_model(ba_2014, type = "pred", terms = c("days", "type"))
logistic.display(ba_2014, decimal = 2, simplified=TRUE)

```

* 2016

```{r}
modEvA::Dsquared(ba_2016)
Anova(ba_2016)
summary(ba_2016)
cm5 <- rbind(
  'Check vs Arbor'   = c(0, 0, 1, 0, 1, 0),
  'Check vs Trellis' = c(0, 0, 0, 1, 0, 1), 
  'Arbor vs Trellis' = c(0, 0, 1, -1, 1, -1))
estimable(ba_2016, cm5)
# plot_model(ba_2016, type = "pred", terms = c("days", "type"))
logistic.display(ba_2016, decimal = 2, simplified=TRUE)
```